spring.application.name=classic-business-model-frontend
server.port=8086

# Backend base URL
backend.base-url=http://localhost:8085

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false